Repository ISISComputingGroup/ibex_bluesky_core, pull requests merged in 2024-09, with the labels that each got.

#29 Update set_up_dev_environment.md
  doc/set_up_dev_environment.md
Labels: size/XS

#27 9 add basic dae signals
  doc/dae/base.md
  doc/dae/controls.md
  doc/dae/settings.md
  doc/dae/spectra.md
  doc/set_up_dev_environment.md
  pyproject.toml
  src/ibex_bluesky_core/demo_plan.py
  src/ibex_bluesky_core/devices/__init__.py
  src/ibex_bluesky_core/devices/dae.py
  src/ibex_bluesky_core/devices/dae/__init__.py
  src/ibex_bluesky_core/devices/dae/dae.py
  src/ibex_bluesky_core/devices/dae/dae_controls.py
  src/ibex_bluesky_core/devices/dae/dae_event_mode.py
  src/ibex_bluesky_core/devices/dae/dae_monitor.py
  src/ibex_bluesky_core/devices/dae/dae_period.py
  src/ibex_bluesky_core/devices/dae/dae_period_settings.py
  src/ibex_bluesky_core/devices/dae/dae_settings.py
  src/ibex_bluesky_core/devices/dae/dae_spectra.py
  src/ibex_bluesky_core/devices/dae/dae_tcb_settings.py
  tests/devices/dae_testing_data.py
  tests/devices/test_dae.py
  tests/devices/test_init.py
Labels: size/XXL

#31 Ticket14 docs webpage
  .github/workflows/documentation.yml
  .gitignore
  doc/_api.rst
  doc/_templates/custom-module-template.rst
  doc/architectural_decisions/001-repo-structure.md
  doc/architectural_decisions/002-use-ophyd-async.md
  doc/architectural_decisions/003-run-in-process.md
  doc/callbacks/docs_logging_callback.md
  doc/callbacks/plotting.md
  doc/conf.py
  doc/dae/base.md
  doc/dae/controls.md
  doc/dae/settings.md
  doc/dae/spectra.md
  doc/dev/create_a_release.md
  doc/dev/set_up_dev_environment.md
  doc/dev/sphinx_notes.md
  doc/devices/blocks.md
  doc/devices/dae.md
  doc/index.rst
  pyproject.toml
  ruff.toml
  src/ibex_bluesky_core/devices/block.py
  src/ibex_bluesky_core/run_engine.py
Labels: size/XL
