Repository ISISComputingGroup/ibex_bluesky_core, pull requests merged in 2024-11, with the labels that each got.

#53 logos
  doc/conf.py
  doc/favicon.png
  doc/logo.png
Labels: size/XS

#54 add logo to README
  README.md
  doc/favicon.png
  doc/logo.png
Labels: size/XS

#47 Add helper for external blocking functions
  doc/index.rst
  doc/plan_stubs/external_code.md
  src/ibex_bluesky_core/plan_stubs/__init__.py
  src/ibex_bluesky_core/run_engine/__init__.py
  src/ibex_bluesky_core/run_engine/_msg_handlers.py
  tests/test_plan_stubs.py
Labels: size/L

#56 add action for checking every day against ophyd-async and bluesky main branches
  .github/workflows/test-against-main.yml
Labels: size/M

#51 Add logging
  .github/workflows/Lint-and-test.yml
  doc/dev/logging.md
  src/ibex_bluesky_core/__init__.py
  src/ibex_bluesky_core/callbacks/__init__.py
  src/ibex_bluesky_core/callbacks/file_logger.py
  src/ibex_bluesky_core/callbacks/fitting/__init__.py
  src/ibex_bluesky_core/callbacks/plotting.py
  src/ibex_bluesky_core/devices/block.py
  src/ibex_bluesky_core/devices/dae/dae.py
  src/ibex_bluesky_core/devices/dae/dae_controls.py
  src/ibex_bluesky_core/devices/dae/dae_period_settings.py
  src/ibex_bluesky_core/devices/dae/dae_settings.py
  src/ibex_bluesky_core/devices/dae/dae_spectra.py
  src/ibex_bluesky_core/devices/dae/dae_tcb_settings.py
  src/ibex_bluesky_core/devices/simpledae/__init__.py
  src/ibex_bluesky_core/devices/simpledae/controllers.py
  src/ibex_bluesky_core/devices/simpledae/reducers.py
  src/ibex_bluesky_core/devices/simpledae/waiters.py
  src/ibex_bluesky_core/log.py
  src/ibex_bluesky_core/logger/logger.py
  src/ibex_bluesky_core/logger/logging.conf
  src/ibex_bluesky_core/preprocessors.py
  src/ibex_bluesky_core/run_engine/__init__.py
  tests/devices/test_block.py
  tests/devices/test_dae.py
  tests/logger/test_logger.py
  tests/test_log.py
Labels: size/L

#59 Update test-against-main.yml
  .github/workflows/test-against-main.yml
Labels: size/XS

#60 Add tutorial
  doc/index.rst
  doc/tutorial/overview.md
Labels: size/L

#61 remove sphinx static dir
  doc/conf.py
Labels: size/XS

#65 Be nitpicky
  doc/conf.py
  pyproject.toml
  src/ibex_bluesky_core/devices/block.py
  src/ibex_bluesky_core/devices/simpledae/waiters.py
Labels: size/S

#76 fixes slit scan guess & unit tests
  doc/fitting/fitting.md
  src/ibex_bluesky_core/callbacks/fitting/fitting_utils.py
  tests/callbacks/fitting/test_fitting_methods.py
Labels: size/M

#82 Are we ready for 3.12 yet?
  .github/workflows/Lint-and-test.yml
  tests/callbacks/test_write_log_callback.py
Labels: size/S

#84 Add 'edit on github' button in corner of docs page
  doc/conf.py
Labels: size/XS

#86 Bump sigstore
  .github/workflows/release.yml
Labels: size/XS

#87 Try dependabot
  .github/dependabot.yml
Labels: size/S
