Repository ISISComputingGroup/ibex_bluesky_core, pull requests merged in 2024-10, with the labels that each got.

#28 20 user facing dae
  doc/devices/dae.md
  pyproject.toml
  src/ibex_bluesky_core/demo_plan.py
  src/ibex_bluesky_core/devices/dae/dae.py
  src/ibex_bluesky_core/devices/dae/dae_controls.py
  src/ibex_bluesky_core/devices/dae/dae_spectra.py
  src/ibex_bluesky_core/devices/simpledae/__init__.py
  src/ibex_bluesky_core/devices/simpledae/controllers.py
  src/ibex_bluesky_core/devices/simpledae/reducers.py
  src/ibex_bluesky_core/devices/simpledae/strategies.py
  src/ibex_bluesky_core/devices/simpledae/waiters.py
  tests/devices/simpledae/conftest.py
  tests/devices/simpledae/test_controllers.py
  tests/devices/simpledae/test_reducers.py
  tests/devices/simpledae/test_simpledae.py
  tests/devices/simpledae/test_waiters.py
  tests/devices/test_dae.py
Labels: size/XXL

#39 Add instructions for testing bluesky in PyDev console
  doc/dev/set_up_dev_environment.md
Labels: size/XS

#34 Fitting Callback
  doc/conf.py
  doc/fitting/fitting.md
  doc/fitting/images_fits/dampedosc.PNG
  doc/fitting/images_fits/erf.png
  doc/fitting/images_fits/erfc.png
  doc/fitting/images_fits/gaussian.png
  doc/fitting/images_fits/lorentzian.png
  doc/fitting/images_fits/slitscan.png
  doc/fitting/images_fits/tophat.png
  doc/fitting/images_fits/trapezoid.png
  doc/fitting/standard_fits.md
  doc/index.rst
  pyproject.toml
  src/ibex_bluesky_core/callbacks/fitting/__init__.py
  src/ibex_bluesky_core/callbacks/fitting/fitting_utils.py
  tests/callbacks/fitting/__init__.py
  tests/callbacks/fitting/test_fitting_callback.py
  tests/callbacks/fitting/test_fitting_methods.py
Labels: size/XXL

#37 Add callback for human-readable-file writing
  doc/callbacks/file_writing.md
  doc/index.rst
  doc/preprocessors/rbnumberpp.md
  manual_system_tests/dae_scan.py
  pyproject.toml
  src/ibex_bluesky_core/callbacks/file_logger.py
  src/ibex_bluesky_core/preprocessors.py
  src/ibex_bluesky_core/run_engine.py
  tests/callbacks/test_write_log_callback.py
  tests/conftest.py
  tests/devices/test_block.py
  tests/devices/test_dae.py
  tests/test_preprocessors.py
Labels: size/L

#36 21 generate dae uncertainties
  doc/architectural_decisions/002-use-ophyd-async.md
  doc/architectural_decisions/004-use-scipp.md
  doc/devices/dae.md
  manual_system_tests/dae_scan.py
  src/ibex_bluesky_core/devices/simpledae/reducers.py
  tests/devices/simpledae/test_reducers.py
Labels: size/L

#40 Ticket 23 configure bluesky logging
  doc/logging/logger.md
  src/ibex_bluesky_core/logger/logger.py
  src/ibex_bluesky_core/logger/logging.conf
  tests/logger/test_logger.py
Labels: size/M

#44 Fixes issues found with linear fitting guess function
  doc/fitting/fitting.md
  doc/fitting/standard_fits.md
  src/ibex_bluesky_core/callbacks/fitting/fitting_utils.py
  tests/callbacks/fitting/test_fitting_methods.py
Labels: size/M

#46 Tidy up docs; add an intro
  README.md
  doc/architectural_decisions/004-use-scipp.md
  doc/dev/logging.md
  doc/index.rst
Labels: size/M
