Repository ISISComputingGroup/ibex_bluesky_core, pull requests merged in 2024-08, with the labels that each got.

#4 Setup ci
  .github/workflows/Lint-and-test.yml
  .github/workflows/release.yml
  README.md
  pyproject.toml
Labels: size/L

#5 Create run engine
  pyproject.toml
  src/ibex_bluesky_core/demo_plan.py
  src/ibex_bluesky_core/run_engine.py
  tests/test_run_engine.py
Labels: size/L

#11 Added document logging & unit tests
  doc/docs_logging_callback.md
  src/ibex_bluesky_core/callbacks/__init__.py
  src/ibex_bluesky_core/callbacks/document_logger.py
  src/ibex_bluesky_core/run_engine.py
  tests/conftest.py
  tests/test_document_logging_callback.py
  tests/test_run_engine.py
Labels: size/M

#16 Move docs to doc folder
  README.md
  doc/create_a_release.md
  doc/set_up_dev_environment.md
Labels: size/M

#17 Improved developer set up documentation
  doc/set_up_dev_environment.md
Labels: size/S

#13 Add basic block signals
  doc/blocks.md
  pyproject.toml
  src/ibex_bluesky_core/callbacks/document_logger.py
  src/ibex_bluesky_core/demo_plan.py
  src/ibex_bluesky_core/devices/block.py
  tests/conftest.py
  tests/devices/test_block.py
  tests/devices/test_dae.py
  tests/devices/test_init.py
  tests/test_document_logging_callback.py
  tests/test_run_engine.py
Labels: size/XL

#18 Add IBEX plotting callback
  doc/plotting.md
  doc/set_up_dev_environment.md
  pyproject.toml
  src/ibex_bluesky_core/callbacks/plotting.py
  src/ibex_bluesky_core/demo_plan.py
  src/ibex_bluesky_core/run_engine.py
  tests/callbacks/__init__.py
  tests/callbacks/test_document_logging_callback.py
  tests/callbacks/test_plotting_callback.py
  tests/test_run_engine.py
Labels: size/L
