Repository ISISComputingGroup/ibex_bluesky_core, pull requests merged in 2025-07, with the labels that each got.

#217 Sleep by default after motor redefine
  doc/plan_stubs/redefining.md
  src/ibex_bluesky_core/plan_stubs.py
Labels: size/S, bluesky-bug

#219 remove set num periods in dae_scan.py
  manual_system_tests/dae_scan.py
Labels: size/XS, bluesky-ignore-for-release

#221 update ADR to include run_plan
  doc/architectural_decisions/003-run-in-process.md
Labels: size/XS, bluesky-documentation, bluesky-ignore-for-release

#200 Polarisation / spin-echo tuning scans
  doc/devices/dae.md
  doc/fitting/fitting.md
  src/ibex_bluesky_core/callbacks/__init__.py
  src/ibex_bluesky_core/callbacks/_fitting.py
  src/ibex_bluesky_core/devices/dae/__init__.py
  src/ibex_bluesky_core/devices/polarisingdae/__init__.py
  src/ibex_bluesky_core/devices/polarisingdae/_reducers.py
  src/ibex_bluesky_core/devices/polarisingdae/_spectra.py
  src/ibex_bluesky_core/devices/simpledae/__init__.py
  src/ibex_bluesky_core/devices/simpledae/_controllers.py
  src/ibex_bluesky_core/devices/simpledae/_reducers.py
  src/ibex_bluesky_core/devices/simpledae/_strategies.py
  src/ibex_bluesky_core/devices/simpledae/_waiters.py
  src/ibex_bluesky_core/run_engine/__init__.py
  src/ibex_bluesky_core/utils.py
  tests/callbacks/fitting/test_chained_fitting_callback.py
  tests/devices/__init__.py
  tests/devices/polarisingdae/__init__.py
  tests/devices/polarisingdae/test_polarising_dae.py
  tests/devices/polarisingdae/test_polarising_reducers.py
  tests/devices/simpledae/__init__.py
  tests/devices/simpledae/test_reducers.py
  tests/devices/simpledae/test_simpledae.py
  tests/test_utils.py
Labels: size/XXL, bluesky-Semver-Minor

#224 Momentum fit
  doc/_static/images_fits/muons_momentum.png
  doc/fitting/standard_fits.md
  src/ibex_bluesky_core/fitting.py
  tests/callbacks/fitting/test_fitting_methods.py
Labels: size/L

#215 Draft ADR 7 (Document decisions relating to file archiving)
  doc/architectural_decisions/007-output-file-archiving.md
  doc/callbacks/plotting.md
  doc/conf.py
  pyproject.toml
Labels: size/L, bluesky-documentation

#236 Correct typos
  doc/fitting/standard_fits.md
Labels: size/XS, bluesky-ignore-for-release

#226 impoved erfc stretch guess
  src/ibex_bluesky_core/fitting.py
  tests/callbacks/fitting/test_fitting_methods.py
Labels: size/L, bluesky-Semver-Minor

#243 fix livefit link
  doc/fitting/fitting.md
Labels: size/XS, bluesky-documentation

#249 Enforce adding release-note labels to PRs
  .github/workflows/check_pr_has_label.yml
Labels: size/S, bluesky-ignore-for-release
