Repository ISISComputingGroup/ibex_bluesky_core, pull requests merged in 2025-04, with the labels that each got.

#171 codeql warning fix
  src/ibex_bluesky_core/log.py
Labels: size/XS

#167 Update workflows & fix pyright issues
  .github/workflows/Lint-and-test.yml
  .github/workflows/test-against-main.yml
  src/ibex_bluesky_core/devices/block.py
  src/ibex_bluesky_core/plans/__init__.py
  tests/callbacks/fitting/test_fitting_methods.py
  tests/devices/test_block.py
Labels: size/L

#172 Reword adrs
  doc/architectural_decisions/001-repo-structure.md
  doc/architectural_decisions/002-use-ophyd-async.md
  doc/architectural_decisions/003-run-in-process.md
  doc/architectural_decisions/004-use-scipp.md
  doc/architectural_decisions/005-variance-addition.md
  doc/architectural_decisions/006-where-to-put-code.md
  doc/conf.py
Labels: size/L

#168 license
  pyproject.toml
Labels: size/XS

#173 allow redefine to be optional for refl param
  doc/plan_stubs/redefining.md
  src/ibex_bluesky_core/devices/reflectometry/__init__.py
  src/ibex_bluesky_core/plan_stubs/__init__.py
  tests/test_plan_stubs.py
Labels: size/M

#178 Badges
  README.md
Labels: size/S

#163 Troubleshooting guide
  doc/conf.py
  doc/dev/troubleshooting.md
Labels: size/L

#182 Add version as metadata
  .gitignore
  pyproject.toml
  src/ibex_bluesky_core/callbacks/__init__.py
  src/ibex_bluesky_core/run_engine/__init__.py
  tests/test_run_engine.py
Labels: size/S

#83 Set uncertainties more correctly
  src/ibex_bluesky_core/callbacks/reflectometry/_det_map.py
  src/ibex_bluesky_core/devices/dae/dae_spectra.py
  src/ibex_bluesky_core/devices/simpledae/reducers.py
  tests/devices/simpledae/test_reducers.py
  tests/devices/test_dae.py
Labels: size/L

#141 Set DAE spectra timeouts
  src/ibex_bluesky_core/devices/dae/_spectra.py
Labels: size/S

#183 Remove ignores
  src/ibex_bluesky_core/devices/simpledae/__init__.py
  src/ibex_bluesky_core/plans/reflectometry/_autoalign.py
Labels: size/XS

#186 Negative trapezoids
  doc/fitting/standard_fits.md
  src/ibex_bluesky_core/fitting.py
  tests/callbacks/fitting/test_fitting_methods.py
Labels: size/L

#187 Optometrise
  src/ibex_bluesky_core/callbacks/__init__.py
  src/ibex_bluesky_core/callbacks/_fitting.py
  src/ibex_bluesky_core/callbacks/_plotting.py
  src/ibex_bluesky_core/plans/reflectometry/_autoalign.py
  src/ibex_bluesky_core/plans/reflectometry/_det_map_align.py
  src/ibex_bluesky_core/run_engine/__init__.py
  src/ibex_bluesky_core/run_engine/_msg_handlers.py
  src/ibex_bluesky_core/utils.py
  tests/callbacks/test_isis_callbacks.py
  tests/plans/test_reflectometry.py
  tests/test_utils.py
Labels: size/L

#185 put fit reports in fitting dir
  src/ibex_bluesky_core/callbacks/_fitting.py
Labels: size/XS
