Repository ISISComputingGroup/ibex_bluesky_core, pull requests merged in 2025-03, with the labels that each got.

#114 add ADR for where to keep plans/devices
  doc/architectural_decisions/006-where-to-put-code.md
Labels: size/M

#124 codeql
  .github/codeql/codeql-config.yml
  .github/workflows/Lint-and-test.yml
Labels: size/S

#123 standardise on plans/devices dir in inst area
  doc/architectural_decisions/006-where-to-put-code.md
Labels: size/XS

#129 Revert "codeql"
  .github/codeql/codeql-config.yml
  .github/workflows/Lint-and-test.yml
Labels: size/S

#127 Create lint-and-test-nightly
  .github/workflows/lint-and-test-nightly
  README.md
Labels: size/S

#130 Rename lint-and-test-nightly to lint-and-test-nightly.yml
  .github/workflows/lint-and-test-nightly.yml
Labels: size/XS

#134 fix pyright issues - missing types for Movable, Locatable on block and dae settings
  src/ibex_bluesky_core/devices/block.py
  src/ibex_bluesky_core/devices/dae/dae_controls.py
  src/ibex_bluesky_core/devices/dae/dae_period_settings.py
  src/ibex_bluesky_core/devices/dae/dae_settings.py
  src/ibex_bluesky_core/devices/dae/dae_tcb_settings.py
Labels: size/S

#111 Add plans
  .github/workflows/Lint-and-test.yml
  doc/devices/dae.md
  doc/index.rst
  doc/plans/plans.md
  manual_system_tests/dae_scan.py
  src/ibex_bluesky_core/callbacks/__init__.py
  src/ibex_bluesky_core/callbacks/_utils.py
  src/ibex_bluesky_core/devices/__init__.py
  src/ibex_bluesky_core/devices/block.py
  src/ibex_bluesky_core/devices/dae/__init__.py
  src/ibex_bluesky_core/devices/dae/dae.py
  src/ibex_bluesky_core/devices/muons/__init__.py
  src/ibex_bluesky_core/devices/reflectometry/__init__.py
  src/ibex_bluesky_core/devices/sans/__init__.py
  src/ibex_bluesky_core/devices/simpledae/__init__.py
  src/ibex_bluesky_core/plan_stubs/__init__.py
  src/ibex_bluesky_core/plans/__init__.py
  src/ibex_bluesky_core/plans/muons/__init__.py
  src/ibex_bluesky_core/plans/reflectometry/__init__.py
  src/ibex_bluesky_core/plans/sans/__init__.py
  src/ibex_bluesky_core/preprocessors.py
  src/ibex_bluesky_core/utils/__init__.py
  tests/devices/simpledae/test_simpledae.py
  tests/devices/test_init.py
  tests/devices/test_reflectometry.py
  tests/plans/__init__.py
  tests/plans/test_init.py
  tests/plans/test_reflectometry.py
  tests/test_utils.py
Labels: size/XXL

#139 add plan stub to set a motor's current position (redefine)
  doc/plan_stubs/redefining.md
  pyproject.toml
  src/ibex_bluesky_core/plan_stubs/__init__.py
  tests/plans/test_init.py
  tests/test_plan_stubs.py
Labels: size/L

#105 78 docs make classfunction names link through to api reference more consistently
  doc/callbacks/docs_logging_callback.md
  doc/callbacks/file_writing.md
  doc/callbacks/plotting.md
  doc/dev/logging.md
  doc/devices/blocks.md
  doc/devices/dae.md
  doc/fitting/fitting.md
  doc/fitting/livefit_logger.md
  doc/fitting/standard_fits.md
  doc/plan_stubs/external_code.md
  doc/plan_stubs/matplotlib_helpers.md
  doc/tutorial/overview.md
Labels: size/L

#143 typo in DEFINE_POS_SP
  src/ibex_bluesky_core/devices/reflectometry/__init__.py
Labels: size/XS

#160 update_oa
  pyproject.toml
Labels: size/XS

#148 allow and set fit to none in plans
  src/ibex_bluesky_core/plans/__init__.py
  src/ibex_bluesky_core/plans/reflectometry/__init__.py
Labels: size/S

#150 Remove wait for CHANGED on a refl param redefine
  src/ibex_bluesky_core/devices/reflectometry/__init__.py
  tests/devices/test_reflectometry.py
  tests/test_plan_stubs.py
Labels: size/M

#161 Updates ibc logo & ico
  README.md
  doc/conf.py
  doc/favicon.png
  doc/favicon.svg
  doc/logo.png
  doc/logo.svg
Labels: size/M

#149 make block_w
  src/ibex_bluesky_core/devices/block.py
  tests/devices/test_block.py
Labels: size/M

#165 Remove clear_checkpoint from call_sync
  doc/plan_stubs/external_code.md
  src/ibex_bluesky_core/plan_stubs/__init__.py
Labels: size/S

#169 Remove reference to "not technique specific"
  README.md
Labels: size/XS
