Repository ISISComputingGroup/ibex_bluesky_core, pull requests merged in 2025-02, with the labels that each got.

#102 ruff fixes
  tests/callbacks/fitting/test_fitting_methods.py
  tests/devices/test_block.py
Labels: size/XS

#98 fix exception if output file (rbnum) dir doesn't exist
  src/ibex_bluesky_core/callbacks/_utils.py
  src/ibex_bluesky_core/callbacks/file_logger.py
  src/ibex_bluesky_core/callbacks/fitting/livefit_logger.py
  tests/callbacks/fitting/test_fit_logging_callback.py
  tests/callbacks/test_write_log_callback.py
Labels: size/L

#108 Fixes ophyd-async testing imports
  tests/devices/simpledae/test_controllers.py
  tests/devices/simpledae/test_reducers.py
  tests/devices/simpledae/test_waiters.py
  tests/devices/test_block.py
  tests/devices/test_dae.py
  tests/test_preprocessors.py
Labels: size/S

#115 remove spectra_1_period_1 from dae
  src/ibex_bluesky_core/devices/dae/dae.py
Labels: size/XS

#117 add some developer resources
  doc/dev/set_up_dev_environment.md
Labels: size/XS

#120 add test-against-main badge to README.md
  README.md
Labels: size/XS
