Repository ISISComputingGroup/ibex_bluesky_core, pull requests merged in 2025-01, with the labels that each got.

#66 Ticket42 sum detect monitor spectra
  doc/devices/dae.md
  pyproject.toml
  src/ibex_bluesky_core/devices/dae/dae_spectra.py
  src/ibex_bluesky_core/devices/simpledae/reducers.py
  src/ibex_bluesky_core/run_engine/__init__.py
  tests/devices/simpledae/test_reducers.py
  tests/devices/test_dae.py
Labels: size/XL

#96 Default Filename and Location
  doc/callbacks/file_writing.md
  manual_system_tests/dae_scan.py
  src/ibex_bluesky_core/callbacks/file_logger.py
  src/ibex_bluesky_core/callbacks/fitting/livefit_logger.py
  tests/callbacks/fitting/test_fit_logging_callback.py
  tests/callbacks/test_write_log_callback.py
Labels: size/L

#95 fix formatting issue with tip in set_up_dev_environment.md
  doc/dev/set_up_dev_environment.md
Labels: size/XS
